### ISSUE TITLE
The AD query failed. Using the alternative protocol (LDAPConnection)

### ISSUE THREAD

**Issue by PrzemyslawKlys** [vletoux/pingcastle#122]
Hi,

Just tried to test the newest release on my test active directory and it fails with the error:

![image](https://user-images.githubusercontent.com/15063294/150402498-00a5dc88-d5d2-4247-b713-c73dfdca9b03.png)

It seems it fails on the test cases that I've done for testing weird objects in AD that I've seen in production. My https://github.com/EvotecIT/Testimo module was failing on those as well when doing ACL checks.

This object has denied permissions so I can't read it, and it has a name with a plus sign. 

```
Enumeration expires at 2022-01-20T19:13:46.4572286Z
Enumeration context is 3cd625f0-e0b2-427a-8b02-57e3902f556b
[19:42:55]Getting Enumerate page 0
[19:42:56]Pull successful
Exception while working on CN=Deny Object,OU=Test \+ Test2,DC=ad,DC=evotec,DC=xyz
Exception: Object reference not set to an instance of an object.
StackTrace:    at PingCastle.Healthcheck.HealthcheckAnalyzer.<>c__DisplayClass14.<GenerateUserData>b__12(ADItem x) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 501
   at PingCastle.ADWS.ADWSConnection.<>c__DisplayClass1.<Enumerate>b__0(ItemListType items) in c:\git\PingCastle\ADWS\ADWSConnection.cs:line 248
   at PingCastle.ADWS.ADWSConnection.EnumerateInternalWithADWS(String distinguishedName, String filter, String[] properties, String scope, ReceiveItems callback) in c:\git\PingCastle\ADWS\ADWSConnection.cs:line 407
   at PingCastle.ADWS.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope) in c:\git\PingCastle\ADWS\ADWebService.cs:line 289
[19:42:56] Running ldap enumeration
BaseObject=SubTree
Filter=(|(&(objectClass=user)(objectCategory=person))(objectcategory=msDS-GroupManagedServiceAccount)(objectcategory=msDS-ManagedServiceAccount))
[19:42:56]Calling FindAll
Exception while working on CN=Deny Object,OU=Test \+ Test2,DC=ad,DC=evotec,DC=xyz
[Red][19:42:56] An exception occured when doing the task: Perform analysis for ad.evotec.xyz
[Red]Note: you can run the program with the switch --log to get more detail
An exception occured when doing the task: Perform analysis for ad.evotec.xyz
[Red]Exception: Object reference not set to an instance of an object.
Type:System.NullReferenceException
[DarkRed]   at PingCastle.Healthcheck.HealthcheckAnalyzer.<>c__DisplayClass14.<GenerateUserData>b__12(ADItem x) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 501
   at PingCastle.ADWS.LDAPConnection.EnumerateInternalWithLDAP(String distinguishedName, String filter, String[] properties, String scope, WorkOnReturnedObjectByADWS callback) in c:\git\PingCastle\ADWS\LDAPConnection.cs:line 127
   at PingCastle.ADWS.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope) in c:\git\PingCastle\ADWS\ADWebService.cs:line 305
   at PingCastle.Healthcheck.HealthcheckAnalyzer.GenerateUserData(ADDomainInfo domainInfo, ADWebService adws) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 512
   at PingCastle.Healthcheck.HealthcheckAnalyzer.PerformAnalyze(PingCastleAnalyzerParameters parameters) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 109
   at PingCastle.Tasks.<>c__DisplayClass12`1.<PerformTheAnalysis>b__11() in c:\git\PingCastle\Tasks.cs:line 403
   at PingCastle.Tasks.StartTask(String taskname, TaskDelegate taskdelegate) in c:\git\PingCastle\Tasks.cs:line 873

```

**Comment by vletoux** [comment]
Why are you testing the release version after 3 public beta ... ?
Anyway i'm looking at it, but i think this is too late for a fix.

Most probably related to the access denied object

**Comment by PrzemyslawKlys** [comment]
Ye, it's not a problem - I just reported an issue, maybe people in production don't have this case in their AD. Whether it gets fixed now or in 6 months - up to you.

**Comment by prashantvidja** [comment]
Hi,

Any fix for this error?

Thanks

**Comment by prashantvidja** [comment]
Thanks for your quick fix.

![image](https://user-images.githubusercontent.com/26060662/151142058-c4530d6c-1303-4eb1-84c4-8a5a4ecbe975.png)
I am getting the above error.

**Comment by vletoux** [comment]
please contact me at support@pingcastle.com
