### ISSUE TITLE
Cannot add multiple HoneyPot Exclusions with DistinguishedName

### ISSUE THREAD

**Issue by faebusihe** [vletoux/pingcastle#226]
When Multiple HoneyPot Exclusions are added with DistinguishedName....:

  
  <honeyPotSettings>
    <HoneyPots>
      <HoneyPot distinguishedName="CN=pot1,CN=Computers,DC=test,DC=mysmartlogon,DC=com"/>
      <HoneyPot distinguishedName="CN=pot2,CN=Computers,DC=test,DC=mysmartlogon,DC=com"/>
    </HoneyPots>
  </honeyPotSettings>

 Pingcastle.exe fails with:

Starting the task: Perform analysis for DOMAIN
[16:44:55] An exception occured when doing the task: Perform analysis for DOMAIN
Note: you can run the program with the switch --log to get more detail
Exception: The entry '' has already been added. (C:\Program Files\PingCastle\PingCastle.exe.Config line 57)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at PingCastle.Healthcheck.HoneyPotSettings.GetEncryptionSettings() in c:\git\PingCastle\Healthcheck\HoneyPotSettings.cs:line 10
   at PingCastle.Healthcheck.HealthcheckAnalyzer.LoadHoneyPotData() in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 184
   at PingCastle.Healthcheck.HealthcheckAnalyzer.PerformAnalyze(PingCastleAnalyzerParameters parameters) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 96
   at PingCastle.Tasks.<>c__DisplayClass18.<PerformTheAnalysis>b__17() in c:\git\PingCastle\Tasks.cs:line 552
   at PingCastle.Tasks.StartTask(String taskname, TaskDelegate taskdelegate) in c:\git\PingCastle\Tasks.cs:line 1371

Version 3.2.0

**Comment by vletoux** [comment]
This is working perfectly:
![image](https://github.com/user-attachments/assets/40f1d52f-ee8d-4084-9ff3-97fdb6b4b001)

This is because you added the honey pot **section** (not a user) more than once - the error message is pretty explicit.
