### ISSUE TITLE
Pingcastle Report Consolidation Error

### ISSUE THREAD

**Issue by christopherbaxter** [vletoux/pingcastle#38]
Hello,

We have been using Pingcastle in our environment, but lately, we are getting an error when trying to consolidate the data. The error we get is 'Exception: Object reference not set to an instance of an object.' The complete error is below:

[12:56:28 PM] An exception occured when doing the task: PingCastle report consolidation (HealthcheckData)
Note: you can run the program with the switch --log to get more detail
Exception: Object reference not set to an instance of an object.
   at PingCastle.Healthcheck.HealthcheckAccountData.Add(HealthcheckAccountData x) in c:\git\PingCastle\Data\HealthcheckData.cs:line 305
   at PingCastle.Report.ReportHealthCheckConsolidation.GenerateUserInformation() in c:\git\PingCastle\Report\ReportHealthCheckConsolidation.cs:line 349
   at PingCastle.Report.ReportBase.GenerateSectionFluid(String title, GenerateContentDelegate generateContent, String selectedTab, Boolean defaultIfTabEmpty) in c:\git\PingCastle\Report\ReportBase.cs:line 710
   at PingCastle.Report.ReportHealthCheckConsolidation.GenerateContent(String selectedTab) in c:\git\PingCastle\Report\ReportHealthCheckConsolidation.cs:line 128
   at PingCastle.Report.ReportHealthCheckConsolidation.GenerateBodyInformation() in c:\git\PingCastle\Report\ReportHealthCheckConsolidation.cs:line 94
   at PingCastle.Report.ReportBase.GenerateReportFile(String filename) in c:\git\PingCastle\Report\ReportBase.cs:line 61
   at PingCastle.Tasks.<ConsolidationTask>b__13[T]() in c:\git\PingCastle\Tasks.cs:line 417
   at PingCastle.Tasks.StartTask(String taskname, TaskDelegate taskdelegate) in c:\git\PingCastle\Tasks.cs:line 787

We also made use of the matrix xlsx file, which I dont seem to be able to generate (even if it works) without the PingcastleReporting executable from version 2.7. How can I generate this file using the new version 2.8.1?

Thank you

**Comment by vletoux** [comment]
Most probably one of the section named "<UserAccountData>" has been manually removed from one of the xml.
If you think this is not the root cause of the problem, please contact support@pingcastle.com with a minimal set of report (probably only one) to reproduce the problem.

**Comment by vletoux** [comment]
`<UserAccountData>`
