### ISSUE TITLE
Unhandled exception in application domain task

### ISSUE THREAD

**Issue by dipshitz** [vletoux/pingcastle#79]
Hi there, thanks for all of your work on PingCastle. 

I ran into an issue auditing my domain:

[2:05:41 AM] Gathering general data
[2:05:42 AM] Gathering user data
[2:06:12 AM] Gathering computer data
[2:06:24 AM] Gathering trust data
[2:06:24 AM] Gathering privileged group and permissions data
[2:06:25 AM] - Initialize
[2:06:26 AM] - Searching for critical and infrastructure objects
[2:06:35 AM] - Collecting objects - Iteration 1
[2:06:51 AM] An exception occured when doing the task: application domain

At this point, the error repeats until PingCastle.exe exits. The exception that were printed to screen:

Exception: A logon request contained an invalid logon type value
   at PingCastle.ADWS.WindowsFileConnection.GetWindowsIdentityForUser(NetworkCredential credential, String optionalRemoteserver) in C:\git\PingCastle\ADWS\WindowsFileConnection.cs:line 120
   at PingCastle.ADWS.WindowsFileConnection..ctor(NetworkCredential credential) in C:\git\PingCastle\ADWS\WindowsFileConnection.cs:line 85
   at PingCastle.ADWS.LDAPConnection.get_FileConnection() in C:\git\PingCastle\ADWS\LDAPConnection.cs:line 232
   at PingCastle.Graph.Export.RelationFactory.AnalyzeGPO(String gpoPath) in C:\git\PingCastle\Graph\Export\RelationFactory.cs:line 509
   at PingCastle.Graph.Export.ExportDataFromActiveDirectoryLive.<>c__DisplayClass19_0.<ExportFilesDataWithImpersonation>b__0() in C:\git\PingCastle\Graph\Export\ExportDataFromActiveDirectoryLive.cs:line 296
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I've tried using both ADWS and LDAP protocols, as well as using command line + interactive menus to run a healthcheck. 

Otherwise, PingCastle runs the scanners fine.

Thanks!

**Comment by vletoux** [comment]
you are using login / password authentication, right ?
Do you enter the user asNETBIOS\user or user@domainfqdn ?

**Comment by dipshitz** [comment]
@vletoux It works when I supplied domain\user as username! I still get an invalid login exception during the run:
> Exception while generating GPO Data: The user name or password is incorrect.

When I ran the scanners, I only used "user" as username without domain\ and supplied domain to --server. 

Nonetheless I have a report now, thank you!

**Comment by vletoux** [comment]
added a remark when the user is not as netbios\user or user@domain
"Beware: the user is not on the form domain\\user or user@domain.com. Most likely the GPO part will trigger an access denied error"
